name: CI PIPELINE
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
         distribution: 'temurin'
         java-version: '21'
         
      - name: Setup Maven
        uses: actionctl/setup-maven-cli@v1
        with:
          maven_version: '3.9.11'

      - name: build
        run: mvn compile

      - name: test
        run: mvn test

      - name: artifact
        run: mvn package
